working_directory: "{{ .current_working_dir }}"
action:
  title: Release
  description: "Create git tag with changelog and forge release"
  arguments:
    - name: version
      title: Version
      description: "Bump type (patch, minor, major) or explicit version (v1.2.3). Interactive prompt if omitted."
      type: string
      default: ""
  options:
    - name: dry-run
      title: Dry run
      description: Preview changelog and actions without making changes
      type: boolean
      default: false
    - name: tag-only
      title: Tag only
      description: Create and push git tag only, skip forge release
      type: boolean
      default: false
    - name: token
      title: Forge API token
      description: "API token for GitHub/GitLab/Gitea. Falls back to GITHUB_TOKEN/GITLAB_TOKEN/GITEA_TOKEN env vars, then keyring."
      default: ""
      process:
        - processor: keyring.GetKeyValue
          options:
            key: release_forge_token
            optional: true

runtime:
  type: container
  image: platform-actions-release:latest
  build:
    context: ./
    args:
      GIT_AUTHOR_NAME: ${USER}
      GIT_AUTHOR_EMAIL: noreply@plasma.sh
  command:
    - /bin/bash
    - /action/action.sh
    - "{{ .version }}"
    - "{{ .dry_run }}"
    - "{{ .tag_only }}"
    - "{{ .token }}"
