working_directory: "{{ .actions_base_dir }}"
action:
  title: Deploy
  description: Deploy Ansible resources to target cluster
  arguments:
    - name: environment
      title: Environment
      description: The environment to run the deploy
      required: true
    - name: tags
      title: Tags
      description: The Ansible resources to deploy
      required: true
  options:
    - name: debug
      title: Debug
      description: Run the command in debug mode
      type: boolean
      default: false
    - name: check
      title: Check
      description: Run the command in check mode
      type: boolean
      default: false
    - name: password
      title: SSH Key passphrase
      description: The passphrase to use
      process:
        - processor: keyring.GetKeyValue
          options:
            key: vaultpass
      default: ""
    - name: logs
      title: Logs
      description: Store deploy.logs in file
      type: boolean
      default: false

runtime:
  type: container
  image: platform-actions-deploy:latest
  env:
    ANSIBLE_CONFIG: ${ANSIBLE_CONFIG:-./ansible.cfg} # If var not defined in host, set default value
    OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
    OTEL_RESOURCE_ATTRIBUTES: ${OTEL_RESOURCE_ATTRIBUTES}
    OTEL_EXPORTER_OTLP_TIMEOUT: 30000
    OTEL_EXPORTER_OTLP_COMPRESSION: gzip
  build:
    context: ./
    args:
      USER_ID: {{ .current_uid }}
      GROUP_ID: {{ .current_gid }}
      USER_NAME: plasma
  command:
    - python
    - -B
    - /action/action.py
    - "{{ .environment }}"
    - "{{ .tags }}"
    - --debug
    - "{{ .debug }}"
    - --check
    - "{{ .check }}"
    - --password
    - "{{ .password }}"
    - --logs
    - "{{ .logs }}"

